env:
  AWS_DEFAULT_REGION: "ap-southeast-2"

steps:
  - name: ":cloudformation: Validate template"
    command: "make validate"
    artifact_paths: 'cloudformation/deploy.yaml'

  - name: ":cloudformation: Validate template"
    command: "make validate"
    artifact_paths: 'cloudformation/deploy.yaml'
    agents:
      queue: 'dev'

  - block: ':shipit: Release'
    branches: 'master'

  - name: ":cloudformation: Deploy template"
    command: "make download deploy"
    branches: 'master'
    concurrency: 1
    concurrency_group: "iam-deploy"
